name: ori-drop
recipe: pantheon
config:
  framework: drupal8
  site: origin-drop-8
  id: 92b23841-0340-4035-ada6-fafaff274539
  #edge: false
  #cache: false
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  node:
    type: node:10
    globals:
      gulp-cli: latest
      yarn: latest
proxy:
  pma:
    - pma-ori-drop.lndo.site
tooling:
  push:
    description: Push only database to dev
    options:
      code:
        default: none
      files:
        default: none
      database:
        default: dev
  pull:
    description: Pull only database
    options:
      code:
        default: none
      files:
        default: none
      database:
        default: live
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
