#!/bin/bash

set -eo pipefail

#
# This script prepares the site-under-test by cloning the database from
# an existing site.
#
# Use EITHER this script OR the re-install-new script; do not run both.
#

# Create a new multidev site to test on
terminus -n env:wake "$TERMINUS_SITE.dev"


if [[ $CIRCLE_BRANCH == "master" ]]; then

   terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes --clone-content --notify="$NOTIFY"

   # Run updatedb to ensure that the cloned database is updated for the new code
   terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- updatedb -y

   # If exported configuration is available, then import it.
   if [ -f "config/system.site.yml" ] ; then
     terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- config-import --yes
   fi

else

    # Search list of Pantheon mutlidevs to see if this branch already exits
    MULTIDEVS=$(terminus multidev:list --field=id --format=string $TERMINUS_SITE)
    CREATE_MULTI_DEV=TRUE

    for i in $MULTIDEVS
    do
        if [[ $i == *$CIRCLE_BRANCH* ]]; then
            echo "Mutidev "$CIRCLE_BRANCH" already exists, push code to it"
            terminus -n build:env:push "$TERMINUS_SITE.$CIRCLE_BRANCH"
            CREATE_MULTI_DEV=FALSE
        fi
    done

    if [ $CREATE_MULTI_DEV == TRUE ]; then
        echo "Mutidev doesnt exist, create a new one"
        terminus -n build:env:create "$TERMINUS_SITE.dev" "$CIRCLE_BRANCH" --yes --clone-content --notify="$NOTIFY"
    fi


   # Run updatedb to ensure that the cloned database is updated for the new code
   terminus -n drush "$TERMINUS_SITE.$CIRCLE_BRANCH" -- updatedb -y

   # If exported configuration is available, then import it.
   if [ -f "config/system.site.yml" ] ; then
     terminus -n drush "$TERMINUS_SITE.$CIRCLE_BRANCH" -- config-import --yes
   fi

fi
