#!/bin/bash

set -eo pipefail

#
# This script prepares the site-under-test by cloning the database from
# an existing site.
#
# Use EITHER this script OR the re-install-new script; do not run both.
#

# Create a new multidev site to test on
terminus -n env:wake "$TERMINUS_SITE.dev"


if [[ $CIRCLE_BRANCH == "master" ]]; then

   terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes --clone-content --notify="$NOTIFY"

   # Run updatedb to ensure that the cloned database is updated for the new code
   terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- updatedb -y

   # If exported configuration is available, then import it.
   if [ -f "config/system.site.yml" ] ; then
     terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- config-import --yes
   fi

else

   terminus -n build:env:create "$TERMINUS_SITE.dev" "$CIRCLE_BRANCH" --yes --clone-content --notify="$NOTIFY"

   # Run updatedb to ensure that the cloned database is updated for the new code
   terminus -n drush "$TERMINUS_SITE.$CIRCLE_BRANCH" -- updatedb -y

   # If exported configuration is available, then import it.
   if [ -f "config/system.site.yml" ] ; then
     terminus -n drush "$TERMINUS_SITE.$CIRCLE_BRANCH" -- config-import --yes
   fi

fi



