module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  advagg: 0
  advagg_bundler: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  efq: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  help: 0
  helper: 0
  history: 0
  hsts: 0
  image: 0
  includer: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  lazy: 0
  link: 0
  link_attributes: 0
  linkit: 0
  media: 0
  media_library: 0
  media_oembed_control: 0
  menu_block: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  node: 0
  options: 0
  origin_extend: 0
  page_cache: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  redis: 0
  responsive_image: 0
  role_delegation: 0
  schema_article: 0
  schema_metatag: 0
  schema_organization: 0
  schema_web_page: 0
  schema_web_site: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_block: 0
  sitemap: 0
  smart_trim: 0
  system: 0
  taxonomy: 0
  text: 0
  tinypng: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  update: 0
  upgrade_status: 0
  user: 0
  view_unpublished: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_ui: 0
  weight: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  origin: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
