image_fields:
  media--image--field_media_image--default: '1'
  media--image--field_media_image--full: '1'
  media--inline_image--field_media_image_1--original: '1'
alter_tag:
  img: img
  iframe: iframe
formatters:
  lazy_responsive_image: lazy_responsive_image
  lazy_image: '0'
skipClass: no-lazy
disabled_paths: /rss.xml
placeholderSrc: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
preferNative: false
lazysizes:
  lazyClass: lazyload
  loadedClass: lazyloaded
  loadingClass: lazyloading
  preloadClass: lazypreload
  errorClass: lazyerror
  autosizesClass: lazyautosizes
  srcAttr: data-src
  srcsetAttr: data-srcset
  sizesAttr: data-sizes
  minSize: 40
  customMedia: {  }
  init: true
  expFactor: 1.5
  hFac: 0.8
  loadMode: 2
  loadHidden: true
  ricTimeout: 0
  throttleDelay: 125
  plugins:
    aspectratio: aspectratio
    object-fit: object-fit
    parent-fit: parent-fit
    unveilhooks: unveilhooks
_core:
  default_config_hash: xyl-p4A82Xm3kNZhEa_8OQtiLdONJ6f1ulqtRZZlEMM
cssEffect: true
