skipClass: no-lazy
placeholderSrc: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
preferNative: false
lazysizes:
  lazyClass: lazyload
  loadedClass: lazyloaded
  loadingClass: lazyloading
  preloadClass: lazypreload
  errorClass: lazyerror
  autosizesClass: lazyautosizes
  srcAttr: data-src
  srcsetAttr: data-srcset
  sizesAttr: data-sizes
  minSize: 40
  customMedia: {  }
  init: true
  expFactor: 1.5
  hFac: 0.8
  loadMode: 2
  loadHidden: true
  ricTimeout: 0
  throttleDelay: 125
  plugins:
    aspectratio: aspectratio
    object-fit: object-fit
    parent-fit: parent-fit
    unveilhooks: unveilhooks
_core:
  default_config_hash: xyl-p4A82Xm3kNZhEa_8OQtiLdONJ6f1ulqtRZZlEMM
cssEffect: true
libraryPath: /libraries/lazysizes
minified: true
disable_admin: true
visibility:
  id: request_path
  pages: /rss.xml
  negate: 0
